# Generated by Django 2.1 on 2018-10-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0002_auto_20180927_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
